import { InvoiceData } from "../types"

export function invoiceTemplate(
  invoice: InvoiceData
) {
  return `

<div class="header">

  <div style="display:flex;justify-content:space-between">

    <div>

      <h2>${invoice.clinic.name}</h2>

      <div>
        ${invoice.clinic.branch_name}
      </div>

      <div>
        ${invoice.clinic.address}
      </div>

      <div>
        ${invoice.clinic.phone}
      </div>

      ${
        invoice.clinic.gst_number
          ? `<div>GST : ${invoice.clinic.gst_number}</div>`
          : ""
      }

    </div>

    <div>

      <h1>TAX INVOICE</h1>

      <div>
        Invoice No:
        ${invoice.invoice_number}
      </div>

      <div>
        Date:
        ${invoice.invoice_date}
      </div>

    </div>

  </div>

</div>

<hr />

<div style="margin:20px 0">

  <strong>Customer</strong>

  <div>${invoice.customer_name}</div>

  ${
    invoice.customer_phone
      ? `<div>${invoice.customer_phone}</div>`
      : ""
  }

</div>

<table>

<thead>

<tr>
<th>#</th>
<th>Product</th>
<th>Batch</th>
<th>Qty</th>
<th>Rate</th>
<th>GST%</th>
<th>Amount</th>
</tr>

</thead>

<tbody>

${invoice.items
  .map(
    (item, index) => `
<tr>

<td>${index + 1}</td>

<td>${item.product_name}</td>

<td>${item.batch_number || ""}</td>

<td>${item.quantity}</td>

<td>${item.rate.toFixed(2)}</td>

<td>${item.gst_percent}</td>

<td>${item.amount.toFixed(2)}</td>

</tr>
`
  )
  .join("")}

</tbody>

</table>

<div style="margin-top:20px">

<table class="summary-table">

<tr>
<td>Subtotal</td>
<td class="text-right">
₹${invoice.subtotal.toFixed(2)}
</td>
</tr>

<tr>
<td>CGST</td>
<td class="text-right">
₹${invoice.cgst.toFixed(2)}
</td>
</tr>

<tr>
<td>SGST</td>
<td class="text-right">
₹${invoice.sgst.toFixed(2)}
</td>
</tr>

<tr>
<td>IGST</td>
<td class="text-right">
₹${invoice.igst.toFixed(2)}
</td>
</tr>

<tr>
<td>Discount</td>
<td class="text-right">
₹${invoice.discount.toFixed(2)}
</td>
</tr>

<tr>

<td>
<strong>Grand Total</strong>
</td>

<td class="text-right">
<strong>
₹${invoice.grand_total.toFixed(2)}
</strong>
</td>

</tr>

</table>

</div>

<div class="footer">

<div style="display:flex;justify-content:space-between">

<div>
Generated by MediQuick ERP
</div>

<div>
Authorized Signature
</div>

</div>

</div>
`
}